### ISSUE TITLE
Travis build fails due to pytest

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/prov-service#51]
>    ImportError: cannot import name 'FileStorage'
> The command "pytest --cov-config=.coveragerc --cov=synprov" exited with 2.

https://travis-ci.com/github/Sage-Bionetworks/prov-service/builds/154791509

**Comment by jaeddy** [comment]
The tests are still passing in my local environment. Looks like there are some mismatches in versions when pytest runs:

**In TravisCI:**
```
platform linux -- Python 3.6.7, pytest-4.3.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/travis/build/Sage-Bionetworks/prov-service, inifile:
plugins: cov-2.8.1
```

**Locally:**
```
platform darwin -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jaeddy/code/github/projects/prov-service
plugins: cov-2.7.1
```

The Python version is also slightly off, but I don't think that should matter. I'm guessing we might need to specify a more recent version of **pytest** or **pluggy** (or both) in `test-requirements.txt`.

**Comment by tschaffter** [comment]
The issue revealed by travis on prov-service  is preventing the execution of prov-service .

```
$ python --version
Python 3.7.7
```

```
$ docker-compose -f docker-compose.sbcp.yml up
Recreating sbcp-neo4j ... done
Recreating sbcp-prov  ... done
Attaching to sbcp-neo4j, sbcp-prov
sbcp-prov     | Traceback (most recent call last):
sbcp-prov     |   File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
sbcp-prov     |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
sbcp-prov     |   File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
sbcp-prov     |     return _get_module_details(pkg_main_name, error)
sbcp-prov     |   File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
sbcp-prov     |     __import__(pkg_name)
sbcp-prov     |   File "/usr/src/app/synprov/__init__.py", line 2, in <module>
sbcp-prov     |     import connexion
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/__init__.py", line 3, in <module>
sbcp-prov     |     from .apis import AbstractAPI  # NOQA
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/__init__.py", line 1, in <module>
sbcp-prov     |     from .abstract import AbstractAPI  # NOQA
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py", line 9, in <module>
sbcp-prov     |     from ..operations import make_operation
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/__init__.py", line 1, in <module>
sbcp-prov     |     from .abstract import AbstractOperation  # noqa
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/operations/abstract.py", line 11, in <module>
sbcp-prov     |     from ..decorators.response import ResponseValidator
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/response.py", line 12, in <module>
sbcp-prov     |     from .validation import ResponseBodyValidator
sbcp-prov     |   File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 9, in <module>
sbcp-prov     |     from werkzeug import FileStorage
sbcp-prov     | ImportError: cannot import name 'FileStorage'
sbcp-prov exited with code 1
sbcp-neo4j    | Changed password for user 'neo4j'.
sbcp-neo4j    | Active database: graph.db
sbcp-neo4j    | Directories in use:
sbcp-neo4j    |   home:         /var/lib/neo4j
sbcp-neo4j    |   config:       /var/lib/neo4j/conf
sbcp-neo4j    |   logs:         /logs
sbcp-neo4j    |   plugins:      /var/lib/neo4j/plugins
sbcp-neo4j    |   import:       /var/lib/neo4j/import
sbcp-neo4j    |   data:         /var/lib/neo4j/data
sbcp-neo4j    |   certificates: /var/lib/neo4j/certificates
sbcp-neo4j    |   run:          /var/lib/neo4j/run
sbcp-neo4j    | Starting Neo4j.
sbcp-neo4j    | 2020-03-24 21:53:43.713+0000 INFO  ======== Neo4j 3.5.14 ========
sbcp-neo4j    | 2020-03-24 21:53:43.730+0000 INFO  Starting...
sbcp-neo4j    | 2020-03-24 21:53:45.883+0000 INFO  Initiating metrics...
sbcp-neo4j    | 2020-03-24 21:53:48.736+0000 INFO  Sending metrics to CSV file at /var/lib/neo4j/metrics
sbcp-neo4j    | 2020-03-24 21:53:49.696+0000 INFO  Bolt enabled on 0.0.0.0:7687.
sbcp-neo4j    | 2020-03-24 21:53:51.730+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.all)
sbcp-neo4j    | 2020-03-24 21:53:51.734+0000 WARN  Server thread metrics not available (missing neo4j.server.threads.jetty.idle)
sbcp-neo4j    | 2020-03-24 21:53:53.519+0000 INFO  Started.
sbcp-neo4j    | 2020-03-24 21:53:53.941+0000 INFO  Mounted REST API at: /db/manage
sbcp-neo4j    | 2020-03-24 21:53:54.111+0000 INFO  Server thread metrics have been registered successfully
sbcp-neo4j    | 2020-03-24 21:53:55.778+0000 INFO  Remote interface available at http://localhost:7474/
^CGracefully stopping... (press Ctrl+C again to force)
Stopping sbcp-neo4j   ... done
```

**Comment by tschaffter** [comment]
FileStorage is imported in ./.codegen/server/controller.mustache

**Comment by tschaffter** [comment]
According to README, the following command should be used to regenerate models and controllers. The issue is that this command seems deprecated.

```
$ npx openapi-generator generate \
>     -c .openapi-generator-config \
>     -t .codegen/server \
>     -Dmodels \
>     -DmodelTests=false \
>     -Dapis \
>     -DapiTests=false \
>     -i synprov/openapi/openapi.yaml \
>     -g python-flask \
>     -o .
Usage: openapi-generator [options] [command]

Options:
  -V, --version                      output the version number
  -d, --sdkDir <sdkDir>              sdkDir, default: process.cwd()/service
  -t, --templatePath <templatePath>  templatePath
  -t, --type <type>                  ts/js, default ts
  -c, --camelCase <camelCase>        filename style, true 为大驼峰，lower 为小驼峰
  -d, --sdkDir <sdkDir>              sdkDir, default: process.cwd()/service
  -t, --templatePath <templatePath>  templatePath
  -t, --type <type>                  ts/js, default ts
  -c, --camelCase <camelCase>        filename style, true 为大驼峰，lower 为小驼峰
  -h, --help                         output usage information

Commands:
  url <url>                          swagger2/oas3 json data url
  data <filePath>                    swagger2/oas3 json data file
  config <cfgPath>                   config path
  *
```

**Comment by tschaffter** [comment]
```
pip install -r requirements.txt .

...
ERROR: py2neo 4.3.0 has requirement click==7.0, but you'll have click 7.1.1 which is incompatible.
ERROR: synprov 0.4.0 has requirement connexion==2.0.0, but you'll have connexion 2.0.2 which is incompatible.
...
```

**Comment by tschaffter** [comment]
Using a clean venv: `python3 -m venv venv`

See all changes performed so far: 

Adding `Werkzeug == 0.16.1` to requirements.txt: `synprov` does not throw the `FileStorage` error, but it does not return and just hang. Is that normal?

Also running `synprov --help` hangs:

```
$ synprov --help

<nothing shown after 1 minute>
```

**Note:** `Werkzeug == 1.0.0` (latest) does not work because it removes lot of deprecated objects

**Comment by tschaffter** [comment]
Commits tracked in #53

**Comment by tschaffter** [comment]
@jaeddy What version of `Werkzeug` is installed in your environment? I tried `0.16.1` because someone said that it fixed his `FileStorage` issue (the same we are facing). However `synprov` now hangs (see above).

**Comment by tschaffter** [comment]
@jaeddy I just had the idea to have a peak inside docker.synapse.org/syn18489221/prov-service:develop :-)

```
# python --version
Python 3.6.9

# pip freeze
certifi==2019.9.11
chardet==3.0.4
Click==7.0
clickclick==1.2.2
colorama==0.4.1
connexion==2.0.2
Flask==1.1.1
healthcheck==1.3.3
idna==2.8
inflection==0.3.1
iso8601==0.1.12
itsdangerous==1.1.0
Jinja2==2.10.3
jsonschema==2.6.0
luqum==0.8.0
MarkupSafe==1.1.1
neobolt==1.7.15
neotime==1.7.4
openapi-spec-validator==0.2.8
ply==3.11
prompt-toolkit==2.0.10
py2neo==4.3.0
Pygments==2.3.1
pyhumps==1.3.1
python-dateutil==2.6.0
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
six==1.12.0
swagger-ui-bundle==0.0.2
urllib3==1.24.3
wcwidth==0.1.7
Werkzeug==0.16.
```

**Comment by jaeddy** [comment]
Thanks @tschaffter! I have `Werkzeug==0.15.5` in my local environment, but I assume that the Docker specs are more reliable (or at least more up-to-date).

**Comment by tschaffter** [comment]
Adding `Werkzeug==0.16.1` to `requirements.txt`, then can run `docker-compose up --build`. However, I receive 404 responses when trying to access the following link specified in the README.md:

- http://localhost:8080/rest/ui/
- http://0.0.0.0:8080/rest/ui/
- http://localhost:8080/rest/openapi.json

EDIT: Wrong URL, see below

```
prov-server    |  * Serving Flask app "synprov.config" (lazy loading)
prov-server    |  * Environment: production
prov-server    |    WARNING: This is a development server. Do not use it in a production deployment.
prov-server    |    Use a production WSGI server instead.
prov-server    |  * Debug mode: off
prov-server    | INFO:werkzeug: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
prov-server    | INFO:werkzeug:172.19.0.1 - - [25/Mar/2020 21:34:37] "GET /rest/openapi.json HTTP/1.1" 404 -
prov-server    | INFO:werkzeug:172.19.0.1 - - [25/Mar/2020 21:35:01] "GET / HTTP/1.1" 404 -
prov-server    | INFO:werkzeug:172.19.0.1 - - [25/Mar/2020 21:35:16] "GET /rest/ui/ HTTP/1.1" 404 -
```

**Comment by tschaffter** [comment]
I can access http://localhost:7474/browser/ after running `docker-compose up --build.` and neo4j seems to work fine.

**Comment by tschaffter** [comment]
Same issue (404 errors) when running docker-compose with the image docker.synapse.org/syn18489221/prov-service:develop instead of building it from source.

**Comment by tschaffter** [comment]
The following links now work:

- http://localhost:8080/rest/v1/ui/
- http://0.0.0.0:8080/rest/v1/ui/
- http://localhost:8080/rest/v1/openapi.json
